version: '3.8'

services:
  message-processor:
    image: message-processor:0.0.1
    volumes:
      - ./data:/data
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"  
    environment:
      - SERIAL_PORT=/dev/ttyACM0
      - BAUDRATE=9600
    restart: "no"

  html-generator:
    image: html_generator:0.0.1
    volumes:
      - ./data:/data
    restart: "no"
    # depends_on:
    #   - message-processor
  
  web:
    image: httpd:latest
    container_name: apache_server
    ports: 
      - "9366:80"  
    volumes: 
      - ./data:/usr/local/apache2/htdocs
